# Site configuration
# 1. Set theme
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# Set theme
theme: alembic-jekyll-theme

# 1. File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 7. Site settings
url: 'https://mydomain.com'
baseurl: ''
title: "Pei-Tz Chiu"
description: "My Website"
permalink: pretty
# logo: "https://www.flaticon.com/svg/vstatic/svg/3917/3917327.svg?token=exp=1655219771~hmac=bc6ecae2b7dfd77e7ed4bf633d71d16e"
email: "y19990828@gmail.com"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: English
  url: /
- title: Chinese
  url: /chinese/
- title: Contact
  url: /contact/
# - title: Blog
#   url: /blog/

# Footer nav
navigation_footer:
- title: Created by Yvette
  url: "#top"

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
#   Twitter: 
  Email: [true](mailto:y19990828@gmail.com)
  LinkedIn: https://www.linkedin.com/in/%E6%B2%9B%E6%85%88-%E9%82%B1-14ba29227/
  GitHub: https://github.com/Yvette0828
  link: https://yvette-website.netlify.app/
  
# 5. Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
