# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: "Pei-Tz Chiu"
description: "My Website"
permalink: pretty
# logo: "https://www.flaticon.com/svg/vstatic/svg/3917/3917327.svg?token=exp=1655219771~hmac=bc6ecae2b7dfd77e7ed4bf633d71d16e"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: English
  url: /
- title: Chinese
  url: /chinese/
- title: Contact
  url: /contact/
# - title: Blog
#   url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

#  Site settings
encoding: utf-8-sig # Make sure the encoding is right
# lang: en-GB # Set the site language
title: "About Me" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: 
"Pei-Tz Chiu  
MBA Student   
Graduate Institute of Information Management   
National Taipei University   
New Taipei City, Taiwan" # Site description and default description, also used in jekyll-seo-tag
url: "https://yvette-website.netlify.app/" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/Yvette0828/MyWebsite"
email: "y19990828@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference
