# Site configuration
# 1. Set theme
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# Set theme
theme: alembic-jekyll-theme

# 1. File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 7. Site settings
url: 'https://mydomain.com'
baseurl: ''
title: "Pei-Tz Chiu"
description: 'This is a personal website about Pei-Tz Chiu, a MBA student at National Taipei University in Taiwan. Click buttons below or "Contact" tab for getting more information about me.'
permalink: pretty
# logo: "https://www.flaticon.com/svg/vstatic/svg/3917/3917327.svg?token=exp=1655219771~hmac=bc6ecae2b7dfd77e7ed4bf633d71d16e"
email: "y19990828@gmail.com"

# Pagination
paginate: 3
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: English
  url: /
- title: Chinese
  url: /chinese/
- title: Search
  url: /search/
- title: Blog
  url: /blog/
- title: Categories
  url: /categories/
- title: Contact
  url: /contact/
# - title: Blog
#   url: /blog/

# Footer nav
navigation_footer:
- title: Created by Yvette
  url: "#top"

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
#   Twitter: 
  LinkedIn: https://www.linkedin.com/in/%E6%B2%9B%E6%85%88-%E9%82%B1-14ba29227/
  GitHub: https://github.com/Yvette0828
  link: https://yvette-website.netlify.app/
  
# 5. Collections
collections:
  posts:
    title: Posts
    output: true
    description: "This page incorporates all my posts which are shown below."
    feature_text: |
      Welcome to My Blog!
    feature_image: "https://images.unsplash.com/photo-1597696929736-6d13bed8e6a8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80"

# 6. Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
